version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/data/postgres
    ports:
      - "54320:5432"

  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KEYCLOAK_USER: user
      KEYCLOAK_PASSWORD: password
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://host.docker.internal:54320/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8383
      TZ: UTC
    volumes:
      - keycloak:/var/lib/keycloak/data
      - ./_infrastructure/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8383:8080"
    command:
      [
        '--verbose',
        'start-dev',
        '--import-realm'
      ]
    depends_on:
      - postgres

volumes:
  postgres:
  keycloak:

